abstract final class AnalyticsEvents {
  static const appOpen = 'app_open';
  static const feedOpen = 'feed_open';
  static const feedRefresh = 'feed_refresh';
  static const feedScroll = 'feed_scroll';
  static const caseView = 'case_view';
  static const caseVote = 'case_vote';
  static const voteOption = 'vote_option';
  static const caseCreateStarted = 'case_create_started';
  static const caseCreated = 'case_created';
  static const caseSaved = 'case_saved';
  static const caseShared = 'case_shared';
  static const premiumPurchase = 'premium_purchase';
  static const profileOpened = 'profile_opened';
  static const savedCasesOpened = 'saved_cases_opened';
  static const premiumBannerClicked = 'premium_banner_clicked';
  static const settingsOpened = 'settings_opened';
  static const caseDetailOpened = 'case_detail_opened';
  static const editProfileOpened = 'edit_profile_opened';
  static const profileUpdated = 'profile_updated';
  static const logout = 'logout';
  static const notificationReceived = 'notification_received';
  static const notificationOpened = 'notification_opened';
  static const notificationDismissed = 'notification_dismissed';
}
